// Image provenance analysis, run entirely in the browser.
//
// Evidence sources, strongest first:
//   1. C2PA Content Credentials, cryptographically verified (c2pa-web, the
//      official CAI WebAssembly build of c2pa-rs) against the C2PA trust list.
//   2. Unsigned markers in readable metadata (XMP, PNG text, EXIF strings).
//   3. Camera metadata (EXIF): presence supports a real capture, absence
//      proves nothing because chat apps strip it.
//
// Ported from the local `image-provenance` tool, including the false-positive
// fixes found by scanning 1000 real images (see README).

import { createC2pa, Reader, Context } from "../vendor/c2pa-web/index.js";
import exifr from "../vendor/exifr.esm.mjs";

export const C2PA_WEB_VERSION = "0.15.3";

// IPTC digital source types (cv.iptc.org/newscodes/digitalsourcetype)
const SOURCE_TYPES = {
  trainedAlgorithmicMedia: ["ai", "Generated by an AI model"],
  compositeWithTrainedAlgorithmicMedia: ["ai", "Composite that includes AI-generated content"],
  compositeSynthetic: ["ai", "Composite that includes synthetic content"],
  algorithmicMedia: ["ai", "Generated algorithmically (no camera capture)"],
  dataDrivenMedia: ["ai", "Generated from data"],
  algorithmicallyEnhanced: ["edit", "Algorithmically enhanced"],
  digitalCreation: ["edit", "Created digitally by a person (not a camera capture)"],
  composite: ["edit", "Composite of multiple images"],
  screenCapture: ["edit", "Screen capture"],
  virtualRecording: ["edit", "Virtual recording"],
  minorHumanEdits: ["edit", "Captured, with minor human edits"],
  humanEdits: ["edit", "Edited by a person"],
  compositeCapture: ["capture", "Composite of multiple camera captures"],
  digitalCapture: ["capture", "Captured by a digital camera"],
  computationalCapture: ["capture", "Camera capture with computational processing"],
  negativeFilm: ["capture", "Scanned from negative film"],
  positiveFilm: ["capture", "Scanned from positive film"],
  print: ["capture", "Scanned from a print"],
};

const ACTIONS = {
  "c2pa.created": "created", "c2pa.opened": "opened", "c2pa.edited": "edited",
  "c2pa.converted": "converted to another format", "c2pa.resized": "resized",
  "c2pa.cropped": "cropped", "c2pa.orientation": "rotated",
  "c2pa.color_adjustments": "colour-adjusted", "c2pa.filtered": "filtered",
  "c2pa.placed": "had content placed into it", "c2pa.removed": "had content removed",
  "c2pa.drawing": "drawn on", "c2pa.watermarked": "watermarked",
  "c2pa.watermarked.bound": "watermarked", "c2pa.watermarked.unbound": "invisibly watermarked",
  "c2pa.transcoded": "transcoded", "c2pa.repackaged": "repackaged",
  "c2pa.published": "published", "c2pa.redacted": "redacted",
  "c2pa.edited.metadata": "metadata edited",
};
const BENIGN_ACTIONS = new Set(["created", "opened", "published"]);

// Unsigned markers: [regex, finding, severity]. Matched only against readable
// text metadata, never compressed data: short names like "xai" occur by chance
// in binary. Editors count only when named as the producing software, because
// Apple and others write Adobe's XMP "photoshop:" namespace and "Photoshop 3.0"
// IPTC blocks without Photoshop being involved.
const EDITOR = String.raw`(?:CreatorTool|Software|softwareAgent)\W{1,4}[^<>"\x00\n]{0,60}?`;
const MARKERS = [
  [/trainedAlgorithmicMedia/, "IPTC source type 'trainedAlgorithmicMedia' (AI-generated) embedded in metadata", "ai"],
  [/compositeWithTrainedAlgorithmicMedia/, "IPTC source type 'composite with AI-generated content' embedded in metadata", "ai"],
  [/Made with Google AI|Edited with Google AI|Google AI/, "Google AI (Gemini/Imagen) marker in metadata", "ai"],
  [/midjourney/i, "Midjourney marker in metadata", "ai"],
  [/\bdall[-· ]?e\b/i, "DALL-E marker in metadata", "ai"],
  [/stable ?diffusion|ComfyUI|\bsdxl\b/i, "Stable Diffusion / ComfyUI marker in metadata", "ai"],
  [/Apple Photos Generative|Clean Up/, "Apple Photos generative edit (Clean Up) recorded in metadata", "ai"],
  [/adobe firefly|generative fill/i, "Adobe Firefly / Generative Fill marker in metadata", "ai"],
  [/\bgrok\b|\bxai\b|\bflux\.?1\b|ideogram|leonardo\.ai/i, "AI image service marker in metadata", "ai"],
  [/tEXtparameters|iTXtparameters/, "PNG 'parameters' text chunk (Stable Diffusion generation settings)", "ai"],
  [/tEXtprompt|tEXtworkflow/, "PNG 'prompt'/'workflow' text chunk (ComfyUI generation settings)", "ai"],
  [new RegExp(EDITOR + "photoshop", "i"), "Edited in Adobe Photoshop (named as the producing software)", "edit"],
  [new RegExp(EDITOR + String.raw`\bGIMP\b`, "i"), "Edited in GIMP (named as the producing software)", "edit"],
  [new RegExp(EDITOR + "(?:snapseed|lightroom|picsart|facetune|canva|pixelmator|affinity)", "i"),
    "Processed by a photo-editing app (named as the producing software)", "edit"],
];

export const FURTHER = {
  openai: {
    title: "OpenAI verification tool",
    url: "https://openai.com/research/verify/",
    text: "Checks for OpenAI's Content Credentials and its SynthID watermark, which survives screenshots, cropping and metadata stripping. Recommended for any image suspected to come from ChatGPT.",
  },
  gemini: {
    title: "Gemini (SynthID)",
    url: "https://gemini.google.com/app",
    text: "Upload the image and ask “Was this made with Google AI?”. Gemini checks for Google's SynthID watermark.",
  },
  cc: {
    title: "Content Credentials Verify",
    url: "https://contentcredentials.org/verify",
    text: "The official C2PA checker. Use it to independently re-verify any Content Credentials result in this report.",
  },
  original: {
    title: "Ask for the original file",
    url: null,
    text: "Messaging apps strip Content Credentials. The file exactly as the customer saved or received it may still carry them.",
  },
};

let c2paPromise = null;
let contextPromise = null;

export function initVerifier() {
  if (!c2paPromise) {
    c2paPromise = createC2pa({ wasmSrc: new URL("../vendor/c2pa-web/resources/c2pa_bg.wasm", import.meta.url).href });
    contextPromise = (async () => {
      const [anchors, ekus, meta] = await Promise.all([
        fetch(new URL("../trust/C2PA-TRUST-LIST.pem", import.meta.url)).then((r) => r.text()),
        fetch(new URL("../trust/valid_eku_oids.cfg", import.meta.url)).then((r) => r.text()),
        fetch(new URL("../trust/meta.json", import.meta.url)).then((r) => r.json()),
      ]);
      // trustConfig is required: without the EKU list, c2pa-web rejects
      // OpenAI's certificate as "missing required EKU" (c2patool accepts it).
      const context = new Context({
        verify: { verifyTrust: true },
        trust: { trustAnchors: anchors, trustConfig: ekus },
      });
      return { context, trust: { changed: meta.changed, checked: meta.checked } };
    })();
  }
  return Promise.all([c2paPromise, contextPromise]);
}

function sniffFormat(b) {
  const s = (i, n) => String.fromCharCode(...b.subarray(i, i + n));
  if (b[0] === 0x89 && s(1, 3) === "PNG") return ["PNG", "image/png"];
  if (b[0] === 0xff && b[1] === 0xd8) return ["JPEG", "image/jpeg"];
  if (s(0, 3) === "GIF") return ["GIF", "image/gif"];
  if (s(0, 4) === "RIFF" && s(8, 4) === "WEBP") return ["WEBP", "image/webp"];
  if (s(4, 4) === "ftyp") {
    const brand = s(8, 4);
    if (/^avi[fs]/.test(brand)) return ["AVIF", "image/avif"];
    if (/^(heic|heix|heim|heis|hevc|mif1|msf1)/.test(brand)) return ["HEIC", "image/heic"];
  }
  if (s(0, 2) === "II" || s(0, 2) === "MM") return ["TIFF", "image/tiff"];
  return ["unknown", ""];
}

// The file minus compressed pixel data. PNG: every chunk but IDAT. JPEG:
// segments before start-of-scan. Anything else: first and last 256 KiB.
function metadataBytes(b) {
  const out = [];
  if (b[0] === 0x89 && b[1] === 0x50) {
    const dv = new DataView(b.buffer, b.byteOffset, b.byteLength);
    let i = 8;
    while (i + 8 <= b.length) {
      const n = dv.getUint32(i);
      const type = String.fromCharCode(...b.subarray(i + 4, i + 8));
      if (type !== "IDAT") out.push(b.subarray(i + 4, Math.min(b.length, i + 8 + n)));
      i += 12 + n;
    }
  } else if (b[0] === 0xff && b[1] === 0xd8) {
    let i = 2;
    while (i + 4 <= b.length && b[i] === 0xff) {
      if (b[i + 1] === 0xda) break; // start of scan: pixel data follows
      const n = (b[i + 2] << 8) | b[i + 3];
      out.push(b.subarray(i + 4, Math.min(b.length, i + 2 + n)));
      i += 2 + n;
    }
  } else {
    out.push(b.subarray(0, 262144), b.subarray(Math.max(262144, b.length - 262144)));
  }
  return out;
}

const latin1 = new TextDecoder("latin1");

// Readable metadata only: XMP packets, PNG text chunks, EXIF strings.
function textMetadata(b, exif) {
  const parts = [];
  for (const seg of metadataBytes(b)) {
    const s = latin1.decode(seg);
    for (const m of s.matchAll(/<x:xmpmeta[\s\S]*?<\/x:xmpmeta>/g)) parts.push(m[0]);
    if (/^(tEXt|iTXt|zTXt)/.test(s)) parts.push(s);
  }
  for (const [k, v] of Object.entries(exif)) if (typeof v === "string") parts.push(`${k}=${v}`);
  return parts.join("\n");
}

async function sha256(b) {
  const d = new Uint8Array(await crypto.subtle.digest("SHA-256", b));
  return Array.from(d, (x) => x.toString(16).padStart(2, "0")).join("");
}

function agentName(a) {
  if (!a) return "";
  if (typeof a === "string") return a;
  return [a.name, a.version].filter(Boolean).join(" ");
}

function manifestChain(store) {
  const manifests = store.manifests || {};
  const order = [];
  const seen = new Set();
  const walk = (label, rel) => {
    if (!label || seen.has(label) || !manifests[label]) return;
    seen.add(label);
    order.push([label, rel, manifests[label]]);
    for (const ing of manifests[label].ingredients || []) walk(ing.active_manifest, ing.relationship || "ingredient");
  };
  walk(store.active_manifest, "active");
  for (const label of Object.keys(manifests)) walk(label, "other");
  return order;
}

async function readC2pa(file, mime) {
  const [c2pa, { context }] = await initVerifier();
  let reader;
  try {
    reader = await Reader.fromBlob(c2pa, mime || undefined, file, context);
  } catch (e) {
    return { error: `${e.name || "Error"}: ${e.message}` };
  }
  if (!reader) return { absent: true };
  try {
    return { store: await reader.manifestStore() };
  } finally {
    await reader.free();
  }
}

// A JPEG thumbnail for display and the PDF; null if the browser can't decode
// the format (e.g. HEIC outside Safari).
async function thumbnail(file, max = 900) {
  try {
    const bmp = await createImageBitmap(file);
    const scale = Math.min(1, max / Math.max(bmp.width, bmp.height));
    const canvas = document.createElement("canvas");
    canvas.width = Math.round(bmp.width * scale);
    canvas.height = Math.round(bmp.height * scale);
    canvas.getContext("2d").drawImage(bmp, 0, 0, canvas.width, canvas.height);
    const dims = [bmp.width, bmp.height];
    bmp.close();
    const blob = await new Promise((res) => canvas.toBlob(res, "image/jpeg", 0.85));
    return { blob, width: canvas.width, height: canvas.height, dims };
  } catch {
    return null;
  }
}

export async function analyse(file) {
  const bytes = new Uint8Array(await file.arrayBuffer());
  const [format, mime] = sniffFormat(bytes);
  let exif = {};
  try {
    exif = (await exifr.parse(bytes, { tiff: true, exif: true, gps: true, xmp: false, iptc: false, icc: false, jfif: false, ihdr: false })) || {};
  } catch { /* unreadable EXIF is reported as absent */ }

  const [hash, c2, thumb] = await Promise.all([sha256(bytes), readC2pa(file, mime), thumbnail(file)]);
  const meta = textMetadata(bytes, exif);
  const findings = [];
  let verdict = "inconclusive";
  let headline = "No provenance data found";
  let c2pa = null;

  if (c2.store) {
    const store = c2.store;
    const state = store.validation_state || "Unknown";
    const failures = (store.validation_results?.activeManifest?.failure || []).map((f) => f.code);
    const chain = manifestChain(store);
    const sourceTypes = [];
    const steps = [];
    for (const [, rel, m] of chain) {
      const gen = (m.claim_generator_info || []).map((g) => agentName(g)).join(", ") || m.claim_generator || "?";
      for (const a of m.assertions || []) {
        if (!a.label?.startsWith("c2pa.actions")) continue;
        for (const act of a.data?.actions || []) {
          const dst = (act.digitalSourceType || "").split("/").pop();
          if (dst) sourceTypes.push(dst);
          steps.push({
            manifest: rel,
            action: ACTIONS[act.action] || act.action,
            when: act.when || "",
            agent: agentName(act.softwareAgent) || gen,
            source: dst ? (SOURCE_TYPES[dst]?.[1] || dst) : "",
          });
        }
      }
    }
    const active = store.manifests[store.active_manifest];
    const sig = active.signature_info || {};
    const actionsAssertion = (active.assertions || []).find((a) => a.label?.startsWith("c2pa.actions"));
    c2pa = {
      state, failures, steps,
      signer: sig.issuer || "?", signerCn: sig.common_name || "", signed: sig.time || "",
      generator: (active.claim_generator_info || []).map((g) => g.name).join(", "),
      ingredients: active.ingredients || [],
      allActions: actionsAssertion?.data?.allActionsIncluded,
    };
    const kinds = new Set(sourceTypes.map((s) => SOURCE_TYPES[s]?.[0] || "unknown"));
    const signer = sig.issuer || "an unknown signer";
    const trusted = state === "Trusted";

    if (state === "Invalid" && failures.some((f) => /dataHash\.mismatch|hashedURI\.mismatch/.test(f))) {
      verdict = "altered";
      headline = "Image was altered after it was signed";
      findings.push(["ai", "Content Credentials do not match the image",
        `The file carries a C2PA manifest signed by ${signer}, but the image data no longer matches the signed hash (${failures.join(", ")}). The pixels were changed after signing.`]);
    } else if (kinds.has("ai")) {
      const aiType = sourceTypes.find((t) => SOURCE_TYPES[t]?.[0] === "ai");
      const aiDesc = SOURCE_TYPES[aiType][1];
      const tool = steps.find((s) => s.source === aiDesc)?.agent || c2pa.generator;
      verdict = "ai";
      headline = trusted ? "AI-generated: confirmed by signed Content Credentials"
        : "AI-generated, per Content Credentials (signature not fully trusted)";
      findings.push(["ai", "Signed provenance record declares AI generation",
        `The file contains a C2PA Content Credentials manifest signed by ${signer}${sig.common_name ? ` (${sig.common_name})` : ""} on ${sig.time || "?"}. It records the image as ${aiDesc[0].toLowerCase() + aiDesc.slice(1)} (${aiType}), produced by ${tool}.`]);
      if (trusted) {
        findings.push(["ai", "Signature verified against the official C2PA trust list",
          "The signing certificate chains to a certificate authority on the C2PA trust list, the claim signature is valid, and the image data matches the signed hash (assertion.dataHash.match). The image has not been modified since the AI service produced it, and the record cannot have been added by a third party without the signer's private key."]);
      } else {
        findings.push(["edit", "Signature not fully trusted",
          `Validation state: ${state}${failures.length ? ` (${failures.join(", ")})` : ""}. The record is present but the signer's identity is not independently vouched for, so treat it as strong indication rather than proof.`]);
      }
    } else if (kinds.has("edit") || steps.some((s) => !BENIGN_ACTIONS.has(s.action))) {
      verdict = "edited";
      headline = "Edited, per Content Credentials";
      findings.push(["edit", "Provenance record shows editing",
        `Signed by ${signer} (state: ${state}). Recorded actions: ${[...new Set(steps.map((s) => s.action))].join(", ")}.`]);
    } else if (kinds.has("capture")) {
      verdict = "capture";
      headline = "Camera capture, per Content Credentials";
      findings.push(["capture", "Provenance record shows a camera capture", `Signed by ${signer} (state: ${state}).`]);
    } else {
      headline = "Content Credentials present, source not declared";
      findings.push(["info", "Content Credentials present", `Signed by ${signer} (state: ${state}), but no source type is declared.`]);
    }

    if (c2pa.ingredients.length) {
      findings.push(["info", `${c2pa.ingredients.length} source image(s) recorded`,
        "The manifest lists input images: " + c2pa.ingredients.map((i) => `${i.title || "?"} (${i.relationship || "?"})`).join(", ") + "."]);
    } else if (verdict === "ai") {
      findings.push(["info", "No source photo is recorded",
        "The manifest lists no input images. That means one of two things: the image was generated outright, or a photo was uploaded and edited but the service does not record uploads as ingredients (ChatGPT, for one, labels both cases 'created'). Either way the file is AI output, not a photograph."]);
    }
  } else if (c2.error) {
    findings.push(["info", "Content Credentials could not be checked", c2.error]);
  } else {
    findings.push(["info", "No Content Credentials",
      "The file has no C2PA manifest. On its own that proves nothing: most cameras do not add one yet, and messaging apps (Slack, WhatsApp, email clients, social media) strip metadata on upload. If possible, ask for the original file as first sent."]);
  }

  const markers = [];
  for (const [rx, text, sev] of MARKERS) {
    if (!rx.test(meta) || markers.includes(text)) continue;
    markers.push(text);
    if (c2pa && sev === "ai" && verdict === "ai") continue; // covered by the signed record
    findings.push([sev, "Unsigned metadata marker",
      `${text}. Embedded markers like this are written by the generating or editing tool; they are not signed, so they support but do not prove the conclusion.`]);
    if (verdict === "inconclusive" || verdict === "capture") {
      verdict = sev === "ai" ? "ai" : "edited";
      headline = sev === "ai" ? "Likely AI-generated (unsigned metadata)" : "Edited (unsigned metadata)";
    }
  }

  const cam = {};
  for (const k of ["Make", "Model", "DateTimeOriginal", "LensModel", "Software"]) if (exif[k]) cam[k] = exif[k] instanceof Date ? exif[k].toISOString().replace("T", " ").slice(0, 19) : String(exif[k]);
  if (exif.latitude != null) cam.GPS = `${exif.latitude.toFixed(5)}, ${exif.longitude.toFixed(5)}`;
  if (cam.Make || cam.Model) {
    findings.push([verdict === "inconclusive" || verdict === "capture" ? "capture" : "info", "Camera metadata present",
      `EXIF identifies ${[cam.Make, cam.Model].filter(Boolean).join(" ")}${cam.DateTimeOriginal ? `, taken ${cam.DateTimeOriginal}` : ""}. EXIF is unsigned and can be copied or edited, so it is supporting evidence only.`]);
  } else {
    findings.push(["info", "No camera metadata",
      "There is no EXIF camera make/model, capture time or GPS. A photo straight from a phone camera normally has these. Their absence is consistent with AI output or a screenshot, but also with any file that has passed through a messaging app."]);
  }
  if (format === "PNG" && !cam.Make && !cam.Model) {
    findings.push(["info", "Saved as PNG",
      "Phone cameras save JPEG or HEIC, not PNG. PNG is typical of screenshots, editing tools and AI image services."]);
  }

  const who = c2pa ? `${c2pa.signer} ${c2pa.generator}`.toLowerCase() : "";
  const further = [];
  if (!c2pa || who.includes("openai")) further.push(FURTHER.openai);
  if (!c2pa || who.includes("google")) further.push(FURTHER.gemini);
  further.push(FURTHER.cc);
  if (!c2pa) further.push(FURTHER.original);

  return {
    name: file.name, size: file.size, sha256: hash, format,
    dims: thumb?.dims || (exif.ExifImageWidth ? [exif.ExifImageWidth, exif.ExifImageHeight] : null),
    thumb, camera: cam, c2pa, c2paError: c2.error || null,
    findings, verdict, headline, markers, further,
    examined: new Date(),
  };
}
